image: node:lts

stages:
  - build
  - pack

webpack:
  stage: build
  dependencies:
    - yarn
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn run build:chromium
    - yarn run build:firefox
  artifacts:
    paths:
      - dist
    untracked: true

zip:
  stage: pack
  dependencies:
    - webpack
  before_script:
    - apt-get update
    - apt-get upgrade
    - apt-get -y install zip
  script:
    - cd dist
    - zip -r ../surround-it-chromium.zip chromium
    - zip -r ../surround-it-firefox.zip firefox
  artifacts:
    paths:
      - surround-it-*.zip
