image: node:lts

stages:
  - build
  - pack

webpack:
  stage: build
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn run build
  artifacts:
    paths:
      - dist
    untracked: true

zip:
  stage: pack
  dependencies:
    - webpack
  before_script:
    - apt-get update
    - apt-get upgrade
    - apt-get -y install zip
  script:
    - cd dist
    - zip -r ../surround-it.zip *
  artifacts:
    paths:
      - surround-it.zip
